#!/bin/bash

# subversion editor setting
export SVN_EDITOR=vim
# Git editor setting
export GIT_EDITOR=vim
# bash default editor setting
export EDITOR=vim

# key-map to invoke "Open vim autochecking for previous vim-sessions"
bind -x '"\C-e":"[ -f Session.vim ] && vim -S Session.vim || vim"'

if [ -d "$(find ~/.vim -type d -name fern.vim | head -n1)" ]; then
	# keymap to invoke "Open vim with Fern file explorer view"
	bind -x '"\C-f":"vim -c '\''Fern . -drawer'\''"'
fi
